GET http://127.0.0.1:8000/products/ HTTP/1.1

###
GET http://127.0.0.1:8000/products/2 HTTP/1.1

###
PUT http://127.0.0.1:8000/products/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1NjI1NDYzLCJpYXQiOjE3NTU2MjUxNjMsImp0aSI6ImY4NTJkZTFkM2ZjNjQ5NmU4Y2I4NWFmNWU1YjlhOGM0IiwidXNlcl9pZCI6IjEifQ.w7nIZyIODGajuZRMfCChn5gN1NdSgCR4ljDJM_KExlA

{
    "name": "A Color Television"
}

###
DELETE http://127.0.0.1:8000/products/2 HTTP/1.1


###
POST http://127.0.0.1:8000/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1NjIxNTg4LCJpYXQiOjE3NTU2MjEyODgsImp0aSI6IjEyNjRkMzhmNjIxYzQwNjBhZTNiZGI2ZjUyMGM4M2YxIiwidXNlcl9pZCI6IjEifQ.VWu-P6HN7ATMBuaTikIvW1KHUlKgmMuGmfeKt9sFYzY

{
    "name": "New Product775",
    "description": "This is a new product775",
    "price": "195.99",
    "stock": 1005
}

### //"7.vento@flauta.6"
POST http://127.0.0.1:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "test"
}

###
POST http://127.0.0.1:8000/api/token/refresh/ HTTP/1.1
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1NTcwODUxNCwiaWF0IjoxNzU1NjIyMTE0LCJqdGkiOiJhZDFlMmZkMjU0ZmM0MWYyOTAwNWQzOWM1MjNkYTIyYyIsInVzZXJfaWQiOiIxIn0.OEpYJTirhkWvQlmcSLU7j5Y2710nHa761g8qEcYhn2o"
}

###
GET http://127.0.0.1:8000/user-orders/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1NjIxNTg4LCJpYXQiOjE3NTU2MjEyODgsImp0aSI6IjEyNjRkMzhmNjIxYzQwNjBhZTNiZGI2ZjUyMGM4M2YxIiwidXNlcl9pZCI6IjEifQ.VWu-P6HN7ATMBuaTikIvW1KHUlKgmMuGmfeKt9sFYzY